# /etc/nginx/nginx.conf
load_module modules/ngx_otel_module.so;

worker_processes auto;
events {
  worker_connections 1024;
}

http {
  otel_service_name end2;

  otel_exporter {
    endpoint otel-collector:4317;
  }

  server {
    listen 80;
    listen [::]:80;
    server_name chat.fiatlux.dev;

    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name www.chat.fiatlux.dev;

    ssl_certificate /etc/ssl/certs/chain.pem;
    ssl_certificate_key /etc/ssl/certs/fiatlux.dev.key;

    return 301 https://chat.fiatlux.dev$request_uri;
  }

  server {
    otel_trace on;
    otel_trace_context propagate;

    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name chat.fiatlux.dev;

    add_header X-Frame-Options DENY always;

    ssl_certificate /etc/ssl/certs/chain.pem;
    ssl_certificate_key /etc/ssl/certs/fiatlux.dev.key;

    ssl_protocols TLSv1.3;
    ssl_ecdh_curve X25519:prime256v1:secp384r1;
    ssl_prefer_server_ciphers off;

    ssl_stapling on;
    ssl_stapling_verify on;

    location / {
      gzip on;

      otel_span_name "$request_method $uri";
      proxy_pass http://frontend:8081; 

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api {
      otel_span_name "$request_method $uri";
      proxy_pass http://backend:8080; 

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # WebSocket support
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location /net {
      otel_span_name "$request_method $uri";
      proxy_pass http://anvil:8545;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # WebSocket support
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      # CORS for viem
      add_header 'Access-Control-Allow-Origin' 'https://chat.fiatlux.dev' always;
      add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
      add_header 'Access-Control-Allow-Headers' 'Content-Type' always;
    }
  }
}